name: pacgal
base: core22
version: '1.0'
license: GPL-2.0-only
summary: Feminized PAC-MAN remake
description: |
  W,A,S,D / Arrow Keys = Move

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]
  - build-on: [armhf]
    build-for: [armhf]

apps:
  pacgal:
    extensions: [gnome]
    command: pacgal
    plugs:
    - desktop
    - desktop-legacy
    - gsettings
    - opengl
    - wayland
    - x11

parts:
  pacgal:
    source: https://github.com/mrbid/PAC-GAL
    source-type: git
    plugin: make
    source-subdir: snap
    build-packages:
    - libglfw3-dev
    stage-packages:
    - libglfw3
    - libgles2
